# CIITM Backend - Project Funding Information
# Support this project and help us build the best institute management system !
# Your support helps us maintain and improve this educational technology platform.

# Buy Me a Coffee
buy_me_a_coffee: abhishek96z

# Custom funding URLs
custom:
  - 'razorpay.me/@NexGenStudioDev'
# How your donations help:
# 🚀 Server hosting and maintenance costs
# 💾 Database and cloud storage expenses
# 🔧 Development tools and services
# 📚 Documentation and learning resources
# 🐛 Bug fixes and security updates
# ✨ New feature development
# 🎓 Educational content creation

# Thank you for supporting open-source education technology! 🙏
